name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build application
      run: make app
    
    - name: Create ZIP archive
      run: |
        cd build
        VERSION=${GITHUB_REF_NAME#v}
        zip -r LogseqTodo-${VERSION}.zip LogseqTodo.app
        shasum -a 256 LogseqTodo-${VERSION}.zip > LogseqTodo-${VERSION}.zip.sha256
        cd ..
    
    - name: Create DMG
      run: make dmg
    
    - name: Generate release notes
      id: release_notes
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        SHA256=$(cat build/LogseqTodo-${VERSION}.zip.sha256 | awk '{print $1}')
        cat << EOF > release_notes.md
        ## 📦 Downloads
        
        - **LogseqTodo-${VERSION}.zip** - App bundle for macOS
        - **LogseqTodo-${VERSION}.dmg** - DMG installer for macOS
        
        ## 🔒 SHA256 Checksums
        
        \`\`\`
        $(cat build/LogseqTodo-${VERSION}.zip.sha256)
        \`\`\`
        
        ## 📋 Requirements
        
        - macOS 15.0 (Sequoia) or later
        - Apple Silicon (M1/M2/M3) Mac
        
        ## 🚀 Installation
        
        ### Using ZIP:
        1. Download \`LogseqTodo-${VERSION}.zip\`
        2. Extract the ZIP file
        3. Move \`LogseqTodo.app\` to your Applications folder
        4. Right-click and select "Open" on first launch
        
        ### Using DMG:
        1. Download \`LogseqTodo-${VERSION}.dmg\`
        2. Open the DMG file
        3. Drag LogseqTodo to your Applications folder
        EOF
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/LogseqTodo-*.zip
          build/LogseqTodo-*.zip.sha256
          build/LogseqTodo-*.dmg
        body_path: release_notes.md
        draft: false
        prerelease: false
        generate_release_notes: true