name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build application
      run: |
        swift build -c release --arch arm64
        mkdir -p build/LogseqTodo.app/Contents/MacOS
        mkdir -p build/LogseqTodo.app/Contents/Resources
        cp .build/arm64-apple-macosx/release/LogseqTodo build/LogseqTodo.app/Contents/MacOS/
        cp Sources/LogseqTodo/Info.plist build/LogseqTodo.app/Contents/
        echo "APPL????" > build/LogseqTodo.app/Contents/PkgInfo
    
    - name: Create ZIP archive
      run: |
        cd build
        zip -r LogseqTodo-${GITHUB_REF_NAME#v}.zip LogseqTodo.app
        cd ..
    
    - name: Generate SHA256
      id: sha256
      run: |
        SHA=$(shasum -a 256 build/LogseqTodo-${GITHUB_REF_NAME#v}.zip | awk '{print $1}')
        echo "sha256=$SHA" >> $GITHUB_OUTPUT
        echo "SHA256: $SHA"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes
          - Initial release
          
          ## SHA256
          `${{ steps.sha256.outputs.sha256 }}`
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/LogseqTodo-${{ github.ref_name }}.zip
        asset_name: LogseqTodo-${{ github.ref_name }}.zip
        asset_content_type: application/zip