name: Update Homebrew Tap

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (without v prefix)'
        required: true
        type: string

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: whywaita/homebrew-tap
          token: ${{ secrets.GITHUB_TOKEN }}
          path: homebrew-tap
      
      - name: Checkout main repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: logseq-todo
      
      - name: Get version and SHA256
        id: release_info
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION_NO_V=${VERSION#v}
            # Download the release asset to calculate SHA256
            wget -q "https://github.com/whywaita/logseq-todo/releases/download/${VERSION}/LogseqTodo-${VERSION_NO_V}.zip"
            SHA256=$(shasum -a 256 LogseqTodo-${VERSION_NO_V}.zip | awk '{print $1}')
          else
            VERSION_NO_V="${{ inputs.version }}"
            VERSION="v${VERSION_NO_V}"
            # Download the release asset to calculate SHA256
            wget -q "https://github.com/whywaita/logseq-todo/releases/download/${VERSION}/LogseqTodo-${VERSION_NO_V}.zip"
            SHA256=$(shasum -a 256 LogseqTodo-${VERSION_NO_V}.zip | awk '{print $1}')
          fi
          
          echo "version=${VERSION_NO_V}" >> $GITHUB_OUTPUT
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION_NO_V}, SHA256: ${SHA256}"
      
      - name: Update Homebrew cask
        run: |
          cd homebrew-tap
          
          # Create Casks directory if it doesn't exist
          mkdir -p Casks
          
          # Generate the cask file from template
          sed -e "s/{{VERSION}}/${{ steps.release_info.outputs.version }}/g" \
              -e "s/{{SHA256}}/${{ steps.release_info.outputs.sha256 }}/g" \
              ../logseq-todo/homebrew/logseq-todo.rb.template > Casks/logseq-todo.rb
          
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Commit and push
          git add Casks/logseq-todo.rb
          git commit -m "Update logseq-todo to version ${{ steps.release_info.outputs.version }}" || echo "No changes to commit"
          git push || echo "Failed to push (might be no changes)"
